export const QueryKey = {
  LIST_FARMS: "LISTFARMS",
  DETAIL_FARM: "DETAILFARM",

  LIST_SPECIES: "LISTSPECIES",
  DETAIL_SPECIES: "DETAILSPECIES",

  LIST_ORDERS: "LISTORDERS",
  DETAIL_ORDER: "DETAILORDER",

  LIST_KOIS: "LISTKOIS",
  DETAIL_KOI: "DETAILKOI",

  LIST_CARTS: "LISTCARTS",

  LIST_FEEDBACKS: "LISTFEEDBACKS",

  LIST_TRAVELS: "LISTTRAVELS",
};
