export const QueryKey = {
  LIST_FARMS: "LISTFARMS",
  DETAIL_FARM: "DETAILFARM",
  CREATE_FARM: "CREATEFARM",
  UPDATE_FARM: "UPDATEFARM",

  LIST_SPECIES_KOI: "LISTSPECIESKOI",
  DETAIL_SPECIES_KOI: "DETAILSPECIESKOI",

  LIST_ORDERS_SERVICES: "LISTORDERSSERVICES",
  LIST_ORDERS_UNAPPROVED: "LISTORDERSUNAPPROVED",
  LIST_ORDERS_PERSONAL: "LISTORDERSPERSONAL",
  LIST_ORDERS_DELIVERED: "LISTORDERSDELIVERED",

  DETAIL_ORDER: "DETAILORDER",

  LIST_KOIS: "LISTKOIS",
  DETAIL_KOI: "DETAILKOI",

  LIST_CARTS: "LISTCARTS",

  LIST_FEEDBACKS: "LISTFEEDBACKS",

  LIST_TRAVELS: "LISTTRAVELS",
};
